In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.1.2 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
a=np.array(30)
print(a)
print("The number of dimension of 'a' is:",a.ndim)
print(type(a))

30
The number of dimension of 'a' is: 0
<class 'numpy.ndarray'>


In [4]:
a=np.array([1,2,3,4])
print(a)
print("The number of dimension of 'a' is:",a.ndim)
print(type(a))

[1 2 3 4]
The number of dimension of 'a' is: 1
<class 'numpy.ndarray'>


In [5]:
a=np.array([[1,2,3,4],[3,4,5,6]])
print(a)
print("The number of dimension of 'a' is:",a.ndim)
print(type(a))

[[1 2 3 4]
 [3 4 5 6]]
The number of dimension of 'a' is: 2
<class 'numpy.ndarray'>


In [6]:
a=np.array([[[1,2,3,4],[3,4,5,6]],[[4,5,6,7],[6,7,8,9]]])
print(a)
print("The number of dimension of 'a' is:",a.ndim)
print(type(a))

[[[1 2 3 4]
  [3 4 5 6]]

 [[4 5 6 7]
  [6 7 8 9]]]
The number of dimension of 'a' is: 3
<class 'numpy.ndarray'>


In [7]:
a=np.array([[[1,2,3,4],[3,4,5,6],[4,5,6,7],[7,8,9,0]]])
print(a)
print("The number of dimension of 'a' is:",a.ndim)
print(type(a))

[[[1 2 3 4]
  [3 4 5 6]
  [4 5 6 7]
  [7 8 9 0]]]
The number of dimension of 'a' is: 3
<class 'numpy.ndarray'>


In [11]:
#array will accept all datatypes
e=np.array([2,5.6,"poojitha",7+9j,True,False])
print(e)
print(type(e))
print(e.ndim)

['2' '5.6' 'poojitha' '(7+9j)' 'True' 'False']
<class 'numpy.ndarray'>
1


In [12]:
#list->it will mwrge both list 
a=[2,3,4,5,6]
b=[5,6,7,8,9]
print(a+b)


[2, 3, 4, 5, 6, 5, 6, 7, 8, 9]


In [13]:
#array->it perform the addition operation of two arrays
a=np.array([2,3,4,5,6])
b=np.array([5,6,7,8,9])
print(a+b)

[ 7  9 11 13 15]


In [14]:
c=np.sum(a)
print(c)

20


In [15]:
d=np.sum(b)
print(d)

35


In [16]:
e=np.mean(a)
print(e)

4.0


In [17]:
f=np.mean(b)
print(f)

7.0
